### ISSUE TITLE
Where-landing page

### ISSUE THREAD

**Issue by philippaMAC** [in-FACt/mac-uk#1]
As a user, I can:
- [x]  see all of MAC-UK's network hubs

- [x] identify the network they are looking for by network hub heading

- [x] select a network hub to take you to which players? view

**Comment by astroash** [comment]
@philippaMAC can we please get a list of potential network hub names?

**Comment by philippaMAC** [comment]
@astroash LB Barnet Reach, LB Havering, St Christopher's Staying Close, Project 10/10 Islington, Project Future Haringey

**Comment by philippaMAC** [comment]
MAC-UK branding guidelines and colour codes:

Primary palette | HEX | RGB CODE
-- | -- | --
  | #000000 | R: 0	G: 0	B: 0
  | #5B005B | R: 91	G: 0	B: 91
  | #E0E0E0 | R: 224G: 224	B: 224
Secondary palette | HEX | RGB CODE
  | #C23290 | R: 194	G: 50		B: 144
  | #E3AD03 | R: 227	G: 173	B: 3

**Comment by philippaMAC** [comment]
The headline typeface for MAC-UK is Helvetica Bold. 
All body copy for MAC-UK is set in the font of Helvetica Neue.

**Comment by philippaMAC** [comment]
![mac-uk logo](https://user-images.githubusercontent.com/33494527/32664513-629ec34e-c629-11e7-9cce-556a1604cb38.jpg)

**Comment by philippaMAC** [comment]
![mac-uk logo white-on-black](https://user-images.githubusercontent.com/33494527/32664550-7c1d8f12-c629-11e7-8fa3-59be1f471caf.jpg)

**Comment by maxgerber** [comment]
Thanks @philippaMAC !
