### ISSUE TITLE
Labels on the planet rotate

### ISSUE THREAD

**Issue by rebecacalvoquintero** [in-FACt/mac-uk#11]
The description on the planet should remain horizontal even when the planet is rotating. I have spent some time on it but could not figure out how to solve this.

![screen shot 2017-11-11 at 22 14 11](https://user-images.githubusercontent.com/23295662/32694021-c0d4aea6-c72d-11e7-8793-f5a0aea895e7.png)

**Comment by maxgerber** [comment]
I love this so much haha.

**Comment by maxgerber** [comment]
My opinion is that we should have a static, non-rotating summary info box on the right hand side which will display this information on click. There will be some kind of marker ( `>> Click here for more info` or the like) which will take us to the organogram view.

**Comment by astroash** [comment]
> My opinion is that we should have a static, non-rotating summary info box on the right hand side which will display this information on click. 

I like this idea. If you go for this you can create a `Msg` to create this content so it doesnt have to be writen in the html. The flow would work something like:
- `onClick` event listeners on each planet that updates `model`
- summary box checks `model` and gets `value` from a record/ object (eg `{ reachTeam : "A multi positional team..." }`)

**Comment by rebecacalvoquintero** [comment]
@maxgerber @astroash coollliooooo!!! I like both ideas! I think it makes much more sense...that way another thing not to worry about :)

**Comment by rebecacalvoquintero** [comment]
@astroash @maxgerber I followed your approach and updated the PR #15 . The css looks like shit and obvs the style has to be changed but at least its more or less functional. And with this done, I am gonna relax ;) u guys r the best ❤️
