### ISSUE TITLE
Changed branch default for QAs

### ISSUE THREAD

**Issue by astroash** [in-FACt/mac-uk#12]
Project is currently being merged into `master` not allowing QAs to check code first. I have made a branch from the first commit named`super-master` and set to default.

New work flow:
- devs merge completed work to `master`
- QA's review and merge `master` into `super-master`

**Comment by rebecacalvoquintero** [comment]
perfect! sounds great!

**Comment by maxgerber** [comment]
Can't see an emoji for superhero so I'll just do a 🎅 which is the closest thing

**Comment by andrewMacmurray** [comment]
This is a good structure 👌. The convention usually is to call them `staging` and `master` (where `staging` is what your `master` branch is at the moment and `master` is your `super-master`)
