### ISSUE TITLE
Do we need a navbar in the first and second page?

### ISSUE THREAD

**Issue by rebecacalvoquintero** [in-FACt/mac-uk#13]
What do you think guys?

Do you think it makes sense to leave the navbar on the first and second page?

**Comment by maxgerber** [comment]
I don't think a navbar is necessary for this project actually as the views are sequential, you have to go through the whole flow for it to make sense, right? My instincts say scrap it

**Comment by astroash** [comment]
Hmm, I think the current navbar isn't much use, but it could be useful to have navigation for `home` `forwards` and `backwards`. I'm also well into bottom navbars for mobile as they look native n slick.
