### ISSUE TITLE
TOO much specificity in the css

### ISSUE THREAD

**Issue by rebecacalvoquintero** [in-FACt/mac-uk#14]
Because of adding descendants selectors in the css and make it too specific it is messing up with the rest of style: we need to specify the z-index of the _li_ otherwise when we click on the icon, the icon will not be able to be clickable as its < our planet z index.

Any solutions guys? Otherwise, its not gonna look pretty.....

**Comment by andrewMacmurray** [comment]
@rebecacalvoquintero could you put a few examples here as to where the css is breaking? (perhaps be a bit more *specific* 😂 😂 )
