### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by philippaMAC** [in-FACt/mac-uk#4]
As a user, I can see the following information for a contact:

- [x] Name, job title, organisation, key contact at MAC-UK, primary user needs, email address, phone number, record of interactions with MAC-UK, private MAC-UK notes about the individual

**Comment by astroash** [comment]
@philippaMAC , is it possible to get an example set of data for a contact. It would be really useful to know what type of text you would like for the following fields:
- primary user needs
- record of interactions with MAC-UK
- private MAC-UK notes about the individual

**Comment by philippaMAC** [comment]
@astroash i thought this would be mocked up data for the prototype version ? so primary user needs = e.g. support young people's housing; record of interactions with MAC-UK = date & key contact e.g. 06/11/17 Andy Hogan; notes = tab to click through (without functionality at this stage)
